services:

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
    volumes:
      - ./mount/postgres:/var/lib/postgresql/data
    restart: always
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]