name: Code Quality Checks
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
jobs:
  CodeQualityChecks:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: example
          POSTGRES_PASSWORD: example
          POSTGRES_DB: example
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Run linter check
      run: make lint-check
    - name: Run formatter check
      run: make format-check
    - name: Run MyPy
      run: make mypy-check
    - name: Tests
      run: |-
        uv run python ./app/manage.py migrate
        pytest ./app
      env:
        DB_NAME: example
        DB_USER: example
        DB_PASSWORD: example
        DB_HOST: postgres
        DB_PORT: 5432
